### ISSUE TITLE
Erro ao fazer busca de publicações

### ISSUE THREAD

**Issue by RodrigoBarros01** [ThielNS/WhyNotRun#9]
Se voce escrever um texto, apagar e tentar escrever de novo, ele da erro.
![image](https://user-images.githubusercontent.com/24298771/34262096-771840c2-e652-11e7-84c7-ec286e204b2b.png)

**Comment by ThielNS** [comment]
O erro era do backend, pois ele não estava validando o texto valzio, por isso retornava erro na listagem
